global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'jenkins-webhook'

receivers:
  - name: 'jenkins-webhook'
    webhook_configs:
      - url: 'http://customjenkins:8080/generic-webhook-trigger/invoke?token=mytoken'
