global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Monitor model service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ["192.168.1.34:8000"]
rule_files:
  - "alert_rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']